### ISSUE TITLE
💡 [FEATURE]: Add encryption and decryption to the API endpoints

### ISSUE THREAD

**Issue by SkidGod4444** [plura-ai/plura#113]
### Describe the feature

All information sent through our API after a request is encrypted and it is decrypted when needed by the frontend. Only use `@plura/crypt` package to perform the task.

### What is the current behaviour?

no encryption or decryption happens.

### Additional context

For additional information, join us https://discord.gg/AEaBWNSgkf

### Would you like to work on this issue?

None

### Please check all the boxes below

- [x] I have read and followed the project's code of conduct
- [X] I have searched for similar issues before creating this one
- [X] I have provided all the necessary information to understand and reproduce the issue
- [X] I am willing to contribute to the resolution of this issue

**Comment by ayushhunt** [comment]
Assign me
