### ISSUE TITLE
💡[FEATURE] : .env.example file should be present in the project

### ISSUE THREAD

**Issue by Subas-mohanty** [plura-ai/plura#131]
### Describe the feature

There should be a file called .env.example or .env.sample for every .env file present across the project. It will be very helpful for the contributors to know which environment variable they should use while setting up the project.

### What is the current behaviour?

There is no .env.example file across the project.

### What was the expected behaviour?

There should be .env.example file with all the environment variables with empty or dummy data.

### Would you like to work on this issue?

Yes

### Please check all the boxes below

- [X] I have read and followed the project's code of conduct
- [X] I have searched for similar issues before creating this one
- [X] I have provided all the necessary information to understand and reproduce the issue
- [X] I am willing to contribute to the resolution of this issue

**Comment by SkidGod4444** [comment]
@Subas-mohanty  assign it to yourself! Thanks
