### ISSUE TITLE
Add Integrations Section: Drag and drop nodes like Zapier

### ISSUE THREAD

**Issue by SkidGod4444** [plura-ai/plura#82]
![image](https://github.com/user-attachments/assets/f02ac4dd-d2ed-40e9-bf6a-4bb0f70e6001)

For the integrations page in `plura-app`, we require `drag-and-drop` node configuration. You can refer to Zapier, and that's what we need.

**Comment by Rock007k** [comment]
assign me

**Comment by rxhul18** [comment]
assign me
